[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimize = true
viaIR = true
remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
    '@solmate=lib/solmate/src/',
]
